name: lint-project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          python3 -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH$PYTHONPATH:kipubot" >> $GITHUB_ENV
      - name: Lint with pylint
        run: |
          pipenv run lint
      - name: Type-check with pytype
        run: |
          pipenv run pytype
