name: lint-project

on: [pull_request, workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint with pylint
        run: |
          poetry run poe lint

      - name: Set testing BOT_TOKEN
        run: |
          echo "BOT_TOKEN=${{secrets.TEST_BOT_TOKEN}}" >> $GITHUB_ENV

      - name: Type-check with pytype
        run: |
          poetry run poe type
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

      - name: Run unit tests
        run: |
          poetry run poe test
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
